// blockRegistry.js

// Stage definitions
export const STAGES = [
  { key: "source", label: "Sources", icon: "Database", number: 1 },
  { key: "transform", label: "Transform / Indicator", icon: "TrendingUp", number: 2 },
  { key: "operator", label: "Operators", icon: "GitBranch", number: 3 },
  { key: "derived", label: "Derived Output", icon: "Layers", number: 4 },
  { key: "classifier", label: "Condition Classifier", icon: "Filter", number: 5 },
  { key: "rule", label: "Rule Block", icon: "BookOpen", number: 6 },
  { key: "logic", label: "Logic Combiner", icon: "Workflow", number: 7 },
  { key: "signal", label: "Signal", icon: "Zap", number: 8 },
  { key: "output", label: "Output", icon: "Monitor", number: 9 },
];

export const CATEGORIES = STAGES.map((s) => ({
  key: s.key,
  label: s.label,
  color: `hsl(var(--node-${s.key}))`,
}));

// Block definitions
export const BLOCKS = [
  // 1. SOURCES
  { id: "src_close", label: "Close", category: "source", group: "Sources", inputs: 0, outputs: 1, outputType: "number", acceptsInputTypes: [] },
  { id: "src_open", label: "Open", category: "source", group: "Sources", inputs: 0, outputs: 1, outputType: "number", acceptsInputTypes: [] },
  { id: "src_high", label: "High", category: "source", group: "Sources", inputs: 0, outputs: 1, outputType: "number", acceptsInputTypes: [] },
  { id: "src_low", label: "Low", category: "source", group: "Sources", inputs: 0, outputs: 1, outputType: "number", acceptsInputTypes: [] },
  { id: "src_volume", label: "Volume", category: "source", group: "Sources", inputs: 0, outputs: 1, outputType: "number", acceptsInputTypes: [] },
  { id: "ohlc", label: "OHLC", category: "source", group: "Sources", inputs: 0, outputs: 1, outputType: "ohlc", acceptsInputTypes: [], description: "Full OHLCV bundle" },
  { id: "src_constant", label: "Constant Value", category: "source", group: "Sources", inputs: 0, outputs: 1, outputType: "number", acceptsInputTypes: [], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },

  // 2. TRANSFORMS
  { id: "tx_typical", label: "Typical Price", category: "transform", group: "Price Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], description: "(H+L+C)/3" },
  { id: "tx_hl2", label: "HL2", category: "transform", group: "Price Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"] },
  { id: "tx_hlc3", label: "HLC3", category: "transform", group: "Price Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"] },
  { id: "tx_ohlc4", label: "OHLC4", category: "transform", group: "Price Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"] },
  { id: "tx_weighted", label: "Weighted Price", category: "transform", group: "Price Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], description: "(H+L+C+C)/4" },
  { id: "tx_median", label: "Median Price", category: "transform", group: "Price Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], description: "Median of H,L" },
  { id: "tx_col_select", label: "Column Select", category: "transform", group: "Column Select", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], description: "Pick OHLCV column", fields: [{ key: "column", label: "Column", type: "select", options: ["open","high","low","close","volume"], default: "close" }] },
  { id: "tx_ret", label: "% Return", category: "transform", group: "Returns", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "tx_logret", label: "Log Return", category: "transform", group: "Returns", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "tx_cumret", label: "Cumulative Return", category: "transform", group: "Returns", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "tx_roll_ret", label: "Rolling Return", category: "transform", group: "Returns", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 5 }] },
  { id: "tx_norm", label: "Normalize", category: "transform", group: "Scaling", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "tx_zscore", label: "Z-Score", category: "transform", group: "Scaling", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "tx_roll_norm", label: "Rolling Normalization", category: "transform", group: "Scaling", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "ind_sma", label: "SMA", category: "transform", group: "Moving Average", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "ind_ema", label: "EMA", category: "transform", group: "Moving Average", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "ind_wma", label: "WMA", category: "transform", group: "Moving Average", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "ind_vwma", label: "VWMA", category: "transform", group: "Moving Average", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "ind_hma", label: "HMA", category: "transform", group: "Moving Average", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "ind_rma", label: "RMA / Wilder MA", category: "transform", group: "Moving Average", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 14 }] },
  { id: "ind_rsi", label: "RSI", category: "transform", group: "Momentum", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 14 }] },
  { id: "ind_macd", label: "MACD", category: "transform", group: "Momentum", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "fast", label: "Fast", type: "number", default: 12 }, { key: "slow", label: "Slow", type: "number", default: 26 }, { key: "signal", label: "Signal", type: "number", default: 9 }] },
  { id: "ind_roc", label: "ROC", category: "transform", group: "Momentum", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 10 }] },
  { id: "ind_atr", label: "ATR", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], fields: [{ key: "period", label: "Period", type: "number", default: 14 }] },
  { id: "tx_true_range", label: "True Range", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], description: "max(H-L, |H-Cp|, |L-Cp|)" },
  { id: "tx_range_pct", label: "Range %", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], description: "True Range / Close × 100" },
  { id: "var_parkinson", label: "Parkinson Volatility", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }] },
  { id: "var_gk", label: "Garman-Klass Volatility", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }] },
  { id: "var_rs", label: "Rogers-Satchell Volatility", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }] },
  { id: "var_range", label: "Range (High-Low)", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], fields: [{ key: "window", label: "Window", type: "number", default: 1 }] },
  { id: "tx_real_vol", label: "Realized Volatility", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "ind_bb", label: "Bollinger Band", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }, { key: "stddev", label: "StdDev", type: "number", default: 2 }] },
  { id: "var_variance", label: "Variance", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }] },
  { id: "var_stddev", label: "Standard Deviation", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }] },
  { id: "var_mean_abs_dev", label: "Mean Absolute Deviation", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }] },
  { id: "var_hist_vol", label: "Historical Volatility", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }, { key: "annualize", label: "Annualize", type: "select", options: ["yes","no"], default: "yes" }] },
  { id: "var_implied_vol", label: "Implied Volatility", category: "transform", group: "Volatility", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], description: "Option price + Spot price", fields: [{ key: "strike", label: "Strike", type: "number", default: 0 }, { key: "expiry", label: "Days to Expiry", type: "number", default: 30 }, { key: "rate", label: "Risk-free Rate %", type: "number", default: 5 }, { key: "type", label: "Option Type", type: "select", options: ["call","put"], default: "call" }] },
  { id: "var_coeff_var", label: "Coefficient of Variation", category: "transform", group: "Volatility", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], description: "Mean + StdDev", fields: [{ key: "window", label: "Window", type: "number", default: 20 }] },
  { id: "var_iqr", label: "Interquartile Range", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }] },
  { id: "var_avg_range_pct", label: "Average Range %", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }] },
  { id: "var_vol_percentile", label: "Volatility Percentile", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "lookback", label: "Lookback", type: "number", default: 252 }] },
  { id: "var_vol_rank", label: "Volatility Rank", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "lookback", label: "Lookback", type: "number", default: 252 }] },
  { id: "var_entropy", label: "Entropy Dispersion", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }, { key: "bins", label: "Bins", type: "number", default: 10 }] },
  { id: "var_variance_ratio", label: "Rolling Variance Ratio", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "short", label: "Short Window", type: "number", default: 10 }, { key: "long", label: "Long Window", type: "number", default: 50 }] },
  { id: "var_zscore_vol", label: "Volatility Z-Score", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 50 }] },
  { id: "var_drawdown_vol", label: "Drawdown Volatility", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 252 }] },
  { id: "var_downside_dev", label: "Downside Deviation", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }, { key: "target", label: "Target Return %", type: "number", default: 0 }] },
  { id: "var_band_width", label: "Band Width", category: "transform", group: "Volatility", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], description: "Bollinger Band Width (Upper-Lower)/Middle", fields: [{ key: "normalize", label: "Normalize", type: "select", options: ["yes","no"], default: "yes" }] },
  { id: "ind_vwap", label: "VWAP", category: "transform", group: "Volume", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"] },
  { id: "ind_obv", label: "OBV", category: "transform", group: "Volume", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"] },
  { id: "tx_gap_up", label: "Gap Up", category: "transform", group: "Gap", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], description: "Open > Prev Close event" },
  { id: "tx_gap_down", label: "Gap Down", category: "transform", group: "Gap", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], description: "Open < Prev Close event" },
  { id: "tx_gap_size", label: "Gap Size", category: "transform", group: "Gap", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"] },
  { id: "tx_gap_pct", label: "Gap %", category: "transform", group: "Gap", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"] },
  { id: "tx_gap_fill", label: "Gap Fill", category: "transform", group: "Gap", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["ohlc"], description: "Gap closed event" },
  { id: "tx_rank", label: "Rank", category: "transform", group: "Rank / Percentile", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 50 }] },
  { id: "tx_percentile", label: "Percentile", category: "transform", group: "Rank / Percentile", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 50 }] },
  { id: "tx_detrend", label: "Detrending", category: "transform", group: "Statistical", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], description: "Remove trend via rolling mean subtract" },
  { id: "tx_deseason", label: "De-seasonalization", category: "transform", group: "Statistical", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], description: "Remove intraday/weekly patterns" },
  { id: "tx_lag", label: "Lag / Shift", category: "transform", group: "Time Series Tools", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Lag", type: "number", default: 1 }] },
  { id: "tx_diff", label: "Differencing", category: "transform", group: "Time Series Tools", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "order", label: "Order", type: "number", default: 1 }] },
  { id: "tx_rolling_window", label: "Rolling Window", category: "transform", group: "Time Series Tools", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Window", type: "number", default: 20 }] },
  { id: "tx_feature_table", label: "Feature Table", category: "transform", group: "Feature Table", inputs: 0, outputs: 1, outputType: "number", acceptsInputTypes: [], description: "Combine multiple series into ML feature matrix", fields: [{ key: "columns", label: "Column Count", type: "number", default: 5 }] },
  { id: "tx_rolling_mean", label: "Rolling Mean", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }] },
  { id: "tx_moving_median", label: "Moving Median", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 20 }] },
  { id: "tx_exp_smooth", label: "Exponential Smoothing", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "alpha", label: "Alpha", type: "number", default: 0.5 }] },
  { id: "tx_kama", label: "KAMA", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Efficiency Period", type: "number", default: 10 }, { key: "fast", label: "Fast SC", type: "number", default: 2 }, { key: "slow", label: "Slow SC", type: "number", default: 30 }] },
  { id: "tx_alma", label: "ALMA", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 9 }, { key: "offset", label: "Offset", type: "number", default: 0.85 }, { key: "sigma", label: "Sigma", type: "number", default: 6 }] },
  { id: "tx_hma", label: "HMA", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 21 }] },
  { id: "tx_dema", label: "DEMA", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "tx_tema", label: "TEMA", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "tx_zero_lag_ema", label: "Zero-Lag EMA", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "tx_tma", label: "TMA", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "tx_gaussian", label: "Gaussian Smoothing", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 9 }, { key: "sigma", label: "Sigma", type: "number", default: 2 }] },
  { id: "tx_kernel", label: "Kernel Smoothing", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "bandwidth", label: "Bandwidth", type: "number", default: 5 }, { key: "kernel", label: "Kernel", type: "select", options: ["gaussian","epanechnikov"], default: "gaussian" }] },
  { id: "tx_savgol", label: "Savitzky-Golay", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 5 }, { key: "order", label: "Polynomial Order", type: "number", default: 2 }] },
  { id: "tx_lowpass", label: "Low-pass Filter", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "cutoff", label: "Cutoff Frequency", type: "number", default: 0.1 }] },
  { id: "tx_kalman", label: "Kalman Filter", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "process_noise", label: "Process Noise", type: "number", default: 0.01 }, { key: "measurement_noise", label: "Measurement Noise", type: "number", default: 0.1 }] },
  { id: "tx_median_filter", label: "Median Filter", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "window", label: "Window", type: "number", default: 5 }] },
  { id: "tx_adaptive_smooth", label: "Adaptive Smoothing", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "method", label: "Method", type: "select", options: ["volatility","efficiency"], default: "volatility" }] },
  { id: "tx_lowess", label: "LOWESS / LOESS", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "span", label: "Span", type: "number", default: 0.3 }, { key: "degree", label: "Degree", type: "number", default: 1 }] },
  { id: "tx_super_smoother", label: "Super Smoother", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 10 }] },
  { id: "tx_ehlers_filter", label: "Ehlers Filter", category: "transform", group: "Smoothing", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Cycle Period", type: "number", default: 20 }] },

  // 3. OPERATORS
  { id: "op_add", label: "Add (+)", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_sub", label: "Subtract (−)", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_mul", label: "Multiply (×)", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_div", label: "Divide (÷)", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_mod", label: "Modulo", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_pow", label: "Power", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 2 }] },
  { id: "op_min", label: "Min", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_max", label: "Max", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_avg", label: "Average", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_diff", label: "Difference", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_weighted_avg", label: "Weighted Average", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "weight", label: "Weight", type: "number", default: 1 }] },
  { id: "op_mean2", label: "Mean of Two", category: "operator", group: "Arithmetic", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_gt", label: "Greater Than (>)", category: "operator", group: "Comparison", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_lt", label: "Less Than (<)", category: "operator", group: "Comparison", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_gte", label: "Greater or Equal (≥)", category: "operator", group: "Comparison", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_lte", label: "Less or Equal (≤)", category: "operator", group: "Comparison", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_eq", label: "Equal (==)", category: "operator", group: "Comparison", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_neq", label: "Not Equal (≠)", category: "operator", group: "Comparison", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "value", label: "Value", type: "number", default: 0 }] },
  { id: "op_xup", label: "Crosses Above", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_xdn", label: "Crosses Below", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_xup_n", label: "Crossed Above in last N", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "n", label: "N", type: "number", default: 5 }] },
  { id: "op_xdn_n", label: "Crossed Below in last N", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "n", label: "N", type: "number", default: 5 }] },
  { id: "op_touch", label: "Touch", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_reject", label: "Reject", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_breakout", label: "Breakout", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_breakdown", label: "Breakdown", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_stayed_above", label: "Stayed Above for N", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "n", label: "N", type: "number", default: 5 }] },
  { id: "op_stayed_below", label: "Stayed Below for N", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "n", label: "N", type: "number", default: 5 }] },
  { id: "op_retest", label: "Retested", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_failed_breakout", label: "Failed Breakout", category: "operator", group: "Crossover", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_between", label: "Between", category: "operator", group: "Range", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "min", label: "Min", type: "number", default: 40 }, { key: "max", label: "Max", type: "number", default: 60 }] },
  { id: "op_notbetween", label: "Not Between", category: "operator", group: "Range", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_inside", label: "Inside Range", category: "operator", group: "Range", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_outside", label: "Outside Range", category: "operator", group: "Range", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_near", label: "Near", category: "operator", group: "Range", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_far", label: "Far", category: "operator", group: "Range", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_within", label: "Within %", category: "operator", group: "Range", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "pct", label: "Percent", type: "number", default: 0.5 }] },
  { id: "op_above_pct", label: "Above by %", category: "operator", group: "Range", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_below_pct", label: "Below by %", category: "operator", group: "Range", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_dist", label: "Distance From", category: "operator", group: "Range", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_dist_pct", label: "Distance %", category: "operator", group: "Range", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_curr", label: "Current Candle", category: "operator", group: "Time", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_prev", label: "Previous Candle", category: "operator", group: "Time", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_n_ago", label: "N Candles Ago", category: "operator", group: "Time", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "n", label: "N", type: "number", default: 1 }] },
  { id: "op_lastn", label: "Last N Candles", category: "operator", group: "Time", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "n", label: "N", type: "number", default: 5 }] },
  { id: "op_highn", label: "Highest in N", category: "operator", group: "Time", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "n", label: "N", type: "number", default: 20 }] },
  { id: "op_lown", label: "Lowest in N", category: "operator", group: "Time", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "n", label: "N", type: "number", default: 20 }] },
  { id: "op_barssince", label: "Bars Since", category: "operator", group: "Time", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_consec", label: "Consecutive N", category: "operator", group: "Time", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "n", label: "N", type: "number", default: 3 }] },
  { id: "op_first_day", label: "First Candle of Day", category: "operator", group: "Time", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_last_day", label: "Last Candle of Day", category: "operator", group: "Time", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_session", label: "Session Time", category: "operator", group: "Time", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_abs", label: "Absolute Value", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_sign", label: "Sign Function", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_floor", label: "Floor", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_ceil", label: "Ceil", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_round", label: "Round", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_frac", label: "Fractional Part", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_recip", label: "Reciprocal (1/x)", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_clamp", label: "Clamp", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "min", label: "Min", type: "number", default: 0 }, { key: "max", label: "Max", type: "number", default: 100 }] },
  { id: "op_log", label: "Log (ln)", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_log10", label: "Log10", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_exp", label: "Exponential", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_sq", label: "Square (x²)", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_sqrt", label: "Square Root (√x)", category: "operator", group: "Unary Math", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_neg", label: "Negation (−x)", category: "operator", group: "Unary Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_pct_chg", label: "Percent Change", category: "operator", group: "Unary Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 1 }] },
  { id: "op_diff_prev", label: "Diff from Previous", category: "operator", group: "Unary Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 1 }] },
  { id: "op_slope", label: "Slope", category: "operator", group: "Unary Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 14 }] },
  { id: "op_norm_mm", label: "Normalize (Min-Max)", category: "operator", group: "Unary Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "op_norm_zs", label: "Z-Score (rolling)", category: "operator", group: "Unary Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "op_pct_rank", label: "Percentile Rank", category: "operator", group: "Unary Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "op_rolling_max", label: "Rolling Max (Highest N)", category: "operator", group: "Unary Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "op_rolling_min", label: "Rolling Min (Lowest N)", category: "operator", group: "Unary Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "op_bars_since", label: "Bars Since", category: "operator", group: "Unary Transform", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_mean", label: "Mean", category: "operator", group: "Statistical", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_median", label: "Median", category: "operator", group: "Statistical", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_stddev", label: "Std Dev", category: "operator", group: "Statistical", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_var", label: "Variance", category: "operator", group: "Statistical", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_zs", label: "Z-Score (static)", category: "operator", group: "Statistical", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_pctile", label: "Percentile", category: "operator", group: "Statistical", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_quantile", label: "Quantile", category: "operator", group: "Statistical", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_outlier", label: "Outlier", category: "operator", group: "Statistical", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "op_corr", label: "Correlation", category: "operator", group: "Statistical", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_cov", label: "Covariance", category: "operator", group: "Statistical", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_beta", label: "Beta", category: "operator", group: "Statistical", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 60 }] },
  { id: "op_rolling_beta", label: "Rolling Beta", category: "operator", group: "Statistical", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 60 }] },
  { id: "op_coint_resid", label: "Co-integration Residual", category: "operator", group: "Statistical", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_pctdiff", label: "% Difference", category: "operator", group: "Relative", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_ratio", label: "Ratio", category: "operator", group: "Relative", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_spread", label: "Spread", category: "operator", group: "Relative", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_std_spread", label: "Standardized Spread", category: "operator", group: "Relative", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "op_rel_strength", label: "Relative Strength", category: "operator", group: "Relative", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { id: "op_ratio_chg", label: "Ratio Change", category: "operator", group: "Relative", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "period", label: "Period", type: "number", default: 1 }] },
  { id: "op_dot_product", label: "Dot Product", category: "operator", group: "Similarity", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_distance", label: "Distance (Euclidean)", category: "operator", group: "Similarity", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_cosine", label: "Cosine Similarity", category: "operator", group: "Similarity", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "op_divergence", label: "Divergence", category: "operator", group: "Divergence", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], description: "Price vs Indicator divergence" },
  { id: "op_slope_diff", label: "Slope Difference", category: "operator", group: "Divergence", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], description: "Fast slope minus slow slope" },
  { id: "op_vol_ratio", label: "Volatility Ratio", category: "operator", group: "Divergence", inputs: 2, outputs: 1, outputType: "number", acceptsInputTypes: ["number"], fields: [{ key: "short", label: "Short Period", type: "number", default: 5 }, { key: "long", label: "Long Period", type: "number", default: 20 }] },
  { id: "op_vol_price_confirm", label: "Volume Price Confirmation", category: "operator", group: "Divergence", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], description: "Price breakout + volume surge" },
  { id: "op_agreement", label: "Agreement", category: "operator", group: "Confirmation", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"], description: "Both signals in same direction" },
  { id: "op_disagreement", label: "Disagreement", category: "operator", group: "Confirmation", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"], description: "Signals conflict" },
  { id: "op_cond_select", label: "Conditional Select", category: "operator", group: "Conditional", inputs: 3, outputs: 1, outputType: "number", acceptsInputTypes: ["any"], description: "If condition, return A else B" },
  { id: "op_hh", label: "Higher High", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_hl", label: "Higher Low", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_lh", label: "Lower High", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_ll", label: "Lower Low", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_inside_bar", label: "Inside Bar", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_outside_bar", label: "Outside Bar", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_doji", label: "Doji", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_hammer", label: "Hammer", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_shooter", label: "Shooting Star", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_engulf_bull", label: "Bullish Engulfing", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_engulf_bear", label: "Bearish Engulfing", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_gap_up", label: "Gap Up", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_gap_dn", label: "Gap Down", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },
  { id: "op_gap_filled", label: "Gap Filled", category: "operator", group: "Pattern", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["ohlc"] },

  // 4. DERIVED
  { id: "der_numeric", label: "Numeric Value", category: "derived", group: "Value", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_boolean", label: "Boolean (True/False)", category: "derived", group: "Value", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"], description: "Pass-through / constant boolean output", fields: [{ key: "default", label: "Default", type: "select", options: ["True","False"], default: "False" }] },
  { id: "der_event", label: "Event", category: "derived", group: "Value", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "der_distance", label: "Distance", category: "derived", group: "Metrics", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_spread", label: "Spread", category: "derived", group: "Metrics", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_band", label: "Band", category: "derived", group: "Derived", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_channel", label: "Channel", category: "derived", group: "Derived", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_zone", label: "Zone", category: "derived", group: "Derived", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_support", label: "Support Level", category: "derived", group: "Derived", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_resistance", label: "Resistance Level", category: "derived", group: "Derived", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_pivot", label: "Pivot Point", category: "derived", group: "Derived", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_regime", label: "Regime", category: "derived", group: "Derived", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "der_score", label: "Score", category: "derived", group: "Derived", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_rank", label: "Rank", category: "derived", group: "Derived", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_probability", label: "Probability", category: "derived", group: "Derived", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_risk", label: "Risk Metric", category: "derived", group: "Derived", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },
  { id: "der_feature", label: "Feature Column", category: "derived", group: "ML", inputs: 1, outputs: 1, outputType: "number", acceptsInputTypes: ["number"] },

  // 5. CLASSIFIER
  { id: "cls_bullish", label: "Bullish", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number","boolean"], fields: [{ key: "threshold", label: "Threshold", type: "number", default: 0 }] },
  { id: "cls_bearish", label: "Bearish", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number","boolean"], fields: [{ key: "threshold", label: "Threshold", type: "number", default: 0 }] },
  { id: "cls_neutral", label: "Neutral", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number","boolean"] },
  { id: "cls_breakout", label: "Breakout", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number","boolean"] },
  { id: "cls_breakdown", label: "Breakdown", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number","boolean"] },
  { id: "cls_reversal", label: "Reversal", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number","boolean"] },
  { id: "cls_continuation", label: "Continuation", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number","boolean"] },
  { id: "cls_high_vol", label: "High Volume", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "threshold", label: "Threshold", type: "number", default: 1.5 }] },
  { id: "cls_low_vol", label: "Low Volume", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "cls_volatile", label: "High Volatility", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "cls_quiet", label: "Low Volatility", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "cls_overbought", label: "Overbought", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "threshold", label: "Threshold", type: "number", default: 70 }] },
  { id: "cls_oversold", label: "Oversold", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "threshold", label: "Threshold", type: "number", default: 30 }] },
  { id: "cls_strong_trend", label: "Strong Trend", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"], fields: [{ key: "adx_min", label: "ADX Min", type: "number", default: 25 }] },
  { id: "cls_weak_trend", label: "Weak Trend", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "cls_sideways", label: "Sideways", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number"] },
  { id: "cls_risky", label: "Risky", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number","boolean"] },
  { id: "cls_no_trade", label: "No Trade", category: "classifier", group: "Classifier", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["number","boolean"] },

  // 6. RULE
  { id: "rule_entry", label: "Entry Rule", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_exit", label: "Exit Rule", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_filter", label: "Filter Rule", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_risk", label: "Risk Rule", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_position", label: "Position Sizing", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_session", label: "Session Filter", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_universe", label: "Universe Filter", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_confirmation", label: "Confirmation Rule", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_rejection", label: "Rejection Rule", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_watchlist", label: "Watchlist Rule", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_regime", label: "Regime Rule", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_stoploss", label: "Stop Loss Rule", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "rule_takeprofit", label: "Take Profit Rule", category: "rule", group: "Rule", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },

  // 7. LOGIC
  { id: "logic_and", label: "AND", category: "logic", group: "Logic", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "logic_or", label: "OR", category: "logic", group: "Logic", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "logic_not", label: "NOT", category: "logic", group: "Logic", inputs: 1, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "logic_xor", label: "XOR", category: "logic", group: "Logic", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "logic_if", label: "IF / ELSE", category: "logic", group: "Logic", inputs: 3, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "logic_seq", label: "Sequence", category: "logic", group: "Logic", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"] },
  { id: "logic_confirm_n", label: "Confirm Within N Candles", category: "logic", group: "Logic", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"], fields: [{ key: "n", label: "N Candles", type: "number", default: 5 }] },
  { id: "logic_priority", label: "Priority", category: "logic", group: "Logic", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"], description: "First true rule wins" },
  { id: "logic_weighted", label: "Weighted Score", category: "logic", group: "Logic", inputs: 2, outputs: 1, outputType: "boolean", acceptsInputTypes: ["boolean"], fields: [{ key: "threshold", label: "Min Score", type: "number", default: 2 }] },

  // 8. SIGNAL
  { id: "sig_buy", label: "Buy", category: "signal", group: "Signal", inputs: 1, outputs: 1, outputType: "action", acceptsInputTypes: ["boolean"] },
  { id: "sig_sell", label: "Sell", category: "signal", group: "Signal", inputs: 1, outputs: 1, outputType: "action", acceptsInputTypes: ["boolean"] },
  { id: "sig_exit", label: "Exit", category: "signal", group: "Signal", inputs: 1, outputs: 1, outputType: "action", acceptsInputTypes: ["boolean"] },
  { id: "sig_sl", label: "Stop Loss", category: "signal", group: "Signal", inputs: 1, outputs: 1, outputType: "action", acceptsInputTypes: ["boolean"], fields: [{ key: "atr_mult", label: "ATR ×", type: "number", default: 1.5 }] },
  { id: "sig_tp", label: "Take Profit", category: "signal", group: "Signal", inputs: 1, outputs: 1, outputType: "action", acceptsInputTypes: ["boolean"], fields: [{ key: "rr", label: "R:R Ratio", type: "number", default: 2 }] },
  { id: "sig_alert", label: "Alert", category: "signal", group: "Signal", inputs: 1, outputs: 1, outputType: "action", acceptsInputTypes: ["boolean"] },
  { id: "sig_watchlist", label: "Watchlist", category: "signal", group: "Signal", inputs: 1, outputs: 1, outputType: "action", acceptsInputTypes: ["boolean"] },
  { id: "sig_avoid", label: "Avoid", category: "signal", group: "Signal", inputs: 1, outputs: 1, outputType: "action", acceptsInputTypes: ["boolean"] },

  // 9. OUTPUT
  { id: "out_overlay", label: "Chart Overlay", category: "output", group: "Output", inputs: 1, outputs: 0, outputType: "any", acceptsInputTypes: ["action"] },
  { id: "out_oscillator", label: "Oscillator Panel", category: "output", group: "Output", inputs: 1, outputs: 0, outputType: "any", acceptsInputTypes: ["action"] },
  { id: "out_table", label: "Table", category: "output", group: "Output", inputs: 1, outputs: 0, outputType: "any", acceptsInputTypes: ["action"] },
  { id: "out_alert", label: "Alert / Webhook", category: "output", group: "Output", inputs: 1, outputs: 0, outputType: "any", acceptsInputTypes: ["action"] },
  { id: "out_backtest", label: "Backtest", category: "output", group: "Output", inputs: 1, outputs: 0, outputType: "any", acceptsInputTypes: ["action"] },
  { id: "out_export", label: "Export CSV", category: "output", group: "Output", inputs: 1, outputs: 0, outputType: "any", acceptsInputTypes: ["action"] },
];

export function isCompatible(block, upstreamOutputType) {
  if (block.acceptsInputTypes.length === 0) return false;
  if (block.acceptsInputTypes.includes("any")) return true;
  return block.acceptsInputTypes.includes(upstreamOutputType);
}

export function getBlock(id) {
  return BLOCKS.find((b) => b.id === id);
}

export function countByCategory(cat) {
  return BLOCKS.filter((b) => b.category === cat).length;
}