export const styles = {
  topBar: {
    height: 44,
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "0 10px",
    borderBottom: "1px solid #ddd",
  },
  menuBtn: {
    fontSize: 18,
    cursor: "pointer",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.3)",
    zIndex:99999,
  },
  drawer: {
    position: "fixed",
    top: 0,
    bottom: 0,
    width: 280,
    transition: "0.25s",
    padding: 12,
    zIndex: 9999999,
    boxShadow: "2px 0 6px rgba(0,0,0,0.2)",
  },
  header: {
    display: "flex",
    gap: 10,
    alignItems: "center",
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    background: "#9c27b0",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 600,
  },
  item: {
    padding: "10px 6px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    cursor: "pointer",
    fontSize: 14,
  },
  toggle: {
    width: 36,
    height: 20,
    borderRadius: 20,
    position: "relative",
    cursor: "pointer",
  },
  knob: {
    width: 16,
    height: 16,
    borderRadius: "50%",
    background: "#fff",
    position: "absolute",
    top: 2,
    transition: "0.2s",
  }
}